const foodsData = [
  {
    id: 0,
    type: "Lunch",
    name: "Asparagus Salad",
    description: "",
    imageFile: "asparagus-salad.jpg",
    price: "$10.99",
  },
  {
    id: 1,
    type: "Dinner",
    name: "Cutlet With Potatoes And Salad",
    description: "",
    imageFile: "cutlet-with-potatoes-and-salad.jpg",
    price: "$10.99",
  },
  {
    id: 2,
    type: "Dinner",
    name: "Grilled Fish Fillet",
    description: "",
    imageFile: "grilled-fish-fillet.jpg",
    price: "$10.99",
  },
  {
    id: 3,
    type: "Dinner",
    name: "Pasta In Thick Sauce",
    description: "",
    imageFile: "pasta-in-thick-sauce.jpg",
    price: "$10.99",
  },
  {
    id: 4,
    type: "Lunch",
    name: "Toasts With Sauce",
    description: "",
    imageFile: "toasts-with-sauce.jpg",
    price: "$10.99",
  },
  {
    id: 5,
    type: "Lunch",
    name: "Beef Burger With Fries",
    description: "",
    imageFile: "beef-burger-with-fries.jpg",
    price: "$10.99",
  },
  {
    id: 6,
    type: "Dinner",
    name: "Falafels With Vegetables",
    description: "",
    imageFile: "falafels-with-vegetables.jpg",
    price: "$10.99",
  },
  {
    id: 7,
    type: "Dinner",
    name: "Cauliflower Potatoes",
    description: "",
    imageFile: "cauliflower-potatoes.jpg",
    price: "$10.99",
  },
  {
    id: 8,
    type: "Breakfast",
    name: "Porridge With Fruits And Nuts",
    description: "",
    imageFile: "porridge-with-fruits-and-nuts.jpg",
    price: "$10.99",
  },
  {
    id: 9,
    type: "Dinner",
    name: "Vegetables Clear Soup",
    description: "",
    imageFile: "vegetables-clear-soup.jpg",
    price: "$10.99",
  },
  {
    id: 10,
    type: "Breakfast",
    name: "Berries Salad",
    description: "",
    imageFile: "berries-salad.jpg",
    price: "$10.99",
  },
  {
    id: 11,
    type: "Breakfast",
    name: "French Toasts With Berries",
    description: "",
    imageFile: "french-toasts-with-berries.jpg",
    price: "$10.99",
  },
  {
    id: 12,
    type: "Breakfast",
    name: "Hummus With Chickpeas",
    description: "",
    imageFile: "hummus-with-chickpeas.jpg",
    price: "$10.99",
  },
  {
    id: 13,
    type: "Lunch",
    name: "Salmon Fillet With Potatoes",
    description: "",
    imageFile: "salmon-fillet-with-potatoes.jpg",
    price: "$10.99",
  },
  {
    id: 14,
    type: "Dinner",
    name: "Vegetables With Rice",
    description: "",
    imageFile: "vegetables-with-rice.jpg",
    price: "$10.99",
  },
  {
    id: 15,
    type: "Breakfast",
    name: "Boiled Egg With Shrimps",
    description: "",
    imageFile: "boiled-egg-with-shrimps.jpg",
    price: "$10.99",
  },
  {
    id: 16,
    type: "Breakfast",
    name: "Fresh Strawberries",
    description: "",
    imageFile: "fresh-strawberries.jpg",
    price: "$10.99",
  },
  {
    id: 17,
    type: "Breakfast",
    name: "Ice Cream Banana Toast",
    description: "",
    imageFile: "ice-cream-banana-toast.jpg",
    price: "$10.99",
  },
  {
    id: 18,
    type: "Lunch",
    name: "Sauteed Chicken With Broccoli",
    description: "",
    imageFile: "sauteed-chicken-with-broccoli.jpg",
    price: "$10.99",
  },
  {
    id: 19,
    type: "Breakfast",
    name: "Waffle With Fruits",
    description: "",
    imageFile: "waffle-with-fruits.jpg",
    price: "$10.99",
  },
  {
    id: 20,
    type: "Lunch",
    name: "Chicken Biryani",
    description: "",
    imageFile: "chicken-biryani.jpg",
    price: "$10.99",
  },
  {
    id: 21,
    type: "Lunch",
    name: "Fried Chicken With Vegetables",
    description: "",
    imageFile: "fried-chicken-with-vegetables.jpg",
    price: "$10.99",
  },
  {
    id: 22,
    type: "Lunch",
    name: "Kale And Raddish Salad",
    description: "",
    imageFile: "kale-and-raddish-salad.jpg",
    price: "$10.99",
  },
  {
    id: 23,
    type: "Lunch",
    name: "Sauteed Jumbo Shrimps",
    description: "",
    imageFile: "sauteed-jumbo-shrimps.jpg",
    price: "$10.99",
  },
  {
    id: 24,
    type: "Dinner",
    name: "Chicken Salad With Cheese",
    description: "",
    imageFile: "chicken-salad-with-cheese.jpg",
    price: "$10.99",
  },
  {
    id: 25,
    type: "Breakfast",
    name: "Fried Egg With Tomatoes",
    description: "",
    imageFile: "fried-egg-with-tomatoes.jpg",
    price: "$10.99",
  },
  {
    id: 26,
    type: "Dinner",
    name: "Okra Appetizer",
    description: "",
    imageFile: "okra-appetizer.jpg",
    price: "$10.99",
  },
  {
    id: 27,
    type: "Lunch",
    name: "Sliced Tomatoes Salad",
    description: "",
    imageFile: "sliced-tomatoes-salad.jpg",
    price: "$10.99",
  },
  {
    id: 28,
    type: "Dinner",
    name: "Chicken Tandoori",
    description: "",
    imageFile: "chicken-tandoori.jpg",
    price: "$10.99",
  },
  {
    id: 29,
    type: "Dinner",
    name: "Green Salad With Cheese Chunks",
    description: "",
    imageFile: "green-salad-with-cheese-chunks.jpg",
    price: "$10.99",
  },
  {
    id: 30,
    type: "Breakfast",
    name: "Omelette With Potatoes",
    description: "",
    imageFile: "omelette-with-potatoes.jpg",
    price: "$10.99",
  },
  {
    id: 31,
    type: "Lunch",
    name: "Soupy Pasta",
    description: "",
    imageFile: "soupy-pasta.jpg",
    price: "$10.99",
  },
  {
    id: 32,
    type: "Breakfast",
    name: "Cinnamon Buns",
    description: "",
    imageFile: "cinnamon-buns.jpg",
    price: "$10.99",
  },
  {
    id: 33,
    type: "Dinner",
    name: "Grilled Chicken With Fries",
    description: "",
    imageFile: "grilled-chicken-with-fries.jpg",
    price: "$10.99",
  },
  {
    id: 34,
    type: "Breakfast",
    name: "Pancake With Butter",
    description: "",
    imageFile: "pancake-with-butter.jpg",
    price: "$10.99",
  },
  {
    id: 35,
    type: "Lunch",
    name: "Three Color Pasta",
    description: "",
    imageFile: "three-color-pasta.jpg",
    price: "$10.99",
  },
];

export default foodsData;
